version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4050:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
    volumes:
    - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.1
    ports:
      - '4051:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  mysql-data: